stages:
  - docker
  - acceptance

build_image:
  stage: docker
  image: docker:19-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375/
  services:
    - docker:dind
  before_script:
    - echo "aqui estoy"
    - echo ${CI_JOB_TOKEN} | docker login --password-stdin -u ${CI_REGISTRY_USER} ${CI_REGISTRY}
  script:
    - docker build . -t ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest

accept:
  stage: acceptance
  script:
    - echo "Estoy en acceptance"





